[default.extend-words]
# abbreviations
FRE = "FRE"
wrk = "wrk"
fo = "fo"
odf = "odf"
ODF = "ODF"
pn = "pn"
PN = "PN"
Ond = "Ond"
ths = "ths"
gti = "gti"
Ded = "Ded"
ue = "ue"
# tags
curren = "curren"
Thi = "Thi"
pard = "pard"
BA = "BA"
PARD = "PARD"
Evn = "Evn"
ment = "ment"
FO = "FO"
FOF = "FOF"
ture = "ture"
headerr = "headerr"
# non-English words or odd spellings or false positives from code variables
dinosaurios = "dinosaurios"
recommande = "recommande"
Persan = "Persan"
ist = "ist"
oder = "oder"
BERKLEY = "BERKLEY"
Programa = "Programa"
objets = "objets"
sur = "sur"
Hel = "Hel"
FORCAST = "FORCAST"
Forcast = "Forcast"
sie = "sie"
Nothin = "Nothin"
tryin = "tryin"
goin = "goin"
Autor = "Autor"
Ful = "Ful"
nd = "nd"
specfy = "specfy"
als = "als"
ein = "ein"
tio = "tio"
ane = "ane"
som = "som"
ther = "ther"
ine = "ine"
wdth = "wdth"
thr = "thr"
aer = "aer"
ure = "ure"
reall = "reall"
Claus = "Claus"
Vas = "Vas"
vas = "vas"
tro = "tro"
valu = "valu"
wher = "wher"
nin = "nin"
DOUT = "DOUT"
optin = "optin"
# misspelled on purpose in examples
specifiy = "specifiy"
Curso = "Curso"
Informacion = "Informacion"
Perspectivas = "Perspectivas"
philosophia = "philosophia"
thm = "thm"
optin = "optin"

[type.svg]
extend-glob = ["*.svg"]
check-file = false

[files]
extend-exclude = ["src/Catch2/", "src/lua/", "docs/projects",
                  "resources/words", "locale/*.po", "examples",
                  "tests/Dictionaries", "tests/germansyllabletests.cpp",
                  "docs/lua-5.4", "installers/windows/messages/messages-es.isl",
                  "installers/windows/messages/messages-pt.isl",
                  "installers/windows/messages/messages-fr.isl",
                  "docs/readability-studio-manual/_extensions/quarto-ext/fontawesome/assets/css/all.min.css",
                  "docs/readability-studio-manual/_extensions/quarto-ext/fontawesome/assets/css/all.css"]
