project:
  output-dir: "docs"
bibliography: cites.bib
metadata:
  pdf-cover: "images/non-generated/api-cover.png"
  pdf-cover-font-color: "255, 255, 255"
  pdf-cover-author-color: "61, 60, 59"
  pdf-cover-background-color: "250, 244, 230"
  theme-color: "240, 108, 2"
  page-side-decoration-color: "0, 0, 0"
  photography-credits: >-
    Cover and interior photographs by the author and from the
    \textit{Images from the History of Medicine} (IHM) collection,
    National Library of Medicine.
book:
  subtitle: Programming Manual
  output-file: "readability-studio-api"
  chapters:
    - index.qmd
    - part: "Classes"
      chapters:
      - standard-project.qmd
      - batch-project.qmd
    - part: "Libraries"
      chapters:
      - libapp.qmd
      - libdebug.qmd
    - part: "Support Types"
      chapters:
      - enums.qmd
format:
  pdf:
    lot: false
    lof: false
