project:
  output-dir: "docs"
links-as-notes: false
metadata:
  pdf-cover: "images/non-generated/sysadmin-cover.png"
  theme-color: "240, 108, 2"
  page-side-decoration-color: "0, 0, 0"
  photography-credits: >-
    Cover and interior photographs by the author and from the
    \textit{Images from the History of Medicine} (IHM) collection,
    National Library of Medicine.
book:
  subtitle: System Administrator Manual
  output-file: "sysadmin-manual"
  chapters:
    - index.qmd
    - part: "Administration"
      chapters:
      - windows-install.qmd
      - macos-install.qmd
      - linux-install.qmd
      - telemetry.qmd
      - reporting-issues.qmd
    - part: "Building from Source"
      chapters:
      - windows-build.qmd
      - macos-build.qmd
      - linux-build.qmd
    - part: "Contributing"
      chapters:
      - contributing.qmd
      - coding-style.qmd
      - code-structure.qmd
      - code-instructions.qmd
      - documentation.qmd
      - resources.qmd
format:
  pdf:
    lot: false
    lof: false
