project:
  output-dir: "docs"
theme-color: "26, 69, 135"
page-side-decoration-color: "0, 128, 128"
links-as-notes: false
pdf-cover: "images/non-generated/sysadmin-cover.png"
book:
  subtitle: System Administrator Manual
  output-file: "sysadmin-manual"
  chapters:
    - index.qmd
    - part: "Administration"
      chapters:
      - windows-install.qmd
      - macos-install.qmd
      - linux-install.qmd
      - telemetry.qmd
      - reporting-issues.qmd
    - part: "Building from Source"
      chapters:
      - windows-build.qmd
      - macos-build.qmd
      - linux-build.qmd
    - part: "Contributing"
      chapters:
      - contributing.qmd
      - coding-style.qmd
      - code-structure.qmd
      - code-instructions.qmd
      - documentation.qmd
      - resources.qmd
format:
  pdf:
    lot: false
    lof: false
