::: {.minipage data-latex="{\textwidth}"}
### `SetSpellCheckerOptions` {#batch-setspellcheckeroptions}

Sets which items the spell checker\index{spell checker} should ignore.

#### Syntax {-}

``` {.lua}
SetSpellCheckerOptions(boolean ignoreProperNouns,
                       boolean ignoreUppercased,
                       boolean ignoreNumerals,
                       boolean ignoreFileAddresses,
                       boolean ignoreProgrammerCode,
                       boolean ignoreSocialMediaTags,
                       boolean ignoreColloquialisms)
```

#### Parameters {-}

**Parameter** | **Description**
| :-- | :-- |
| `boolean` ignoreProperNouns | `true` to ignore proper nouns. |
| `boolean` ignoreUppercased | `true` to ignore uppercased words. |
| `boolean` ignoreNumerals | `true` to ignore numerals. |
| `boolean` ignoreFileAddresses | `true` to ignore filepaths and URLs. |
| `boolean` ignoreProgrammerCode | `true` to ignore programmer code. |
| `boolean` ignoreSocialMediaTags | `true` to ignore social media tags (e.g., *#goreadabilityformulas*). |
| `boolean` ignoreColloquialisms | `true` to ignore social colloquialisms (e.g., *rockin'*). |

:::: {.tipsection data-latex=""}
This can be optimized by placing it in between calls to [`DelayReloading()`](#batch-delayreloading) and [`Reload()`](#batch-reload).
::::
:::
