# Automatically generated from 'list-files.cmake'
# DO NOT MODIFY MANUALLY!

SET(APP_SRC_FILES
    src/app/readability_app.cpp
    src/app/readability_app_options.cpp
    src/document-helpers/chapter_split.cpp
    src/graphs/frasegraph.cpp
    src/graphs/frygraph.cpp
    src/graphs/polygon_readability_graph.cpp
    src/graphs/raygorgraph.cpp
    src/graphs/schwartzgraph.cpp
    src/indexing/abbreviation.cpp
    src/indexing/article.cpp
    src/indexing/conjunction.cpp
    src/indexing/contraction.cpp
    src/indexing/diacritics.cpp
    src/indexing/double_words.cpp
    src/indexing/negating_word.cpp
    src/indexing/passive_voice.cpp
    src/indexing/pronoun.cpp
    src/indexing/romanize.cpp
    src/indexing/stop_lists.cpp
    src/indexing/syllable.cpp
    src/indexing/word_functional.cpp
    src/lua-scripting/lua_application.cpp
    src/lua-scripting/lua_batch_project.cpp
    src/lua-scripting/lua_debug.cpp
    src/lua-scripting/lua_interface.cpp
    src/lua-scripting/lua_screenshot.cpp
    src/lua-scripting/lua_standard_project.cpp
    src/lua-scripting/onelua_no_warnings.c
    src/projects/base_project.cpp
    src/projects/base_project_doc.cpp
    src/projects/base_project_view.cpp
    src/projects/batch_project_doc.cpp
    src/projects/batch_project_view.cpp
    src/projects/project_frame.cpp
    src/projects/standard_project_doc.cpp
    src/projects/standard_project_view.cpp
    src/results-format/project_report_format.cpp
    src/results-format/readability_messages.cpp
    src/test-helpers/readability_formula_parser.cpp
    src/tinyexpr-plusplus/tinyexpr.cpp
    src/tinyxml2/tinyxml2.cpp
    src/ui/controls/explanation_listctrl.cpp
    src/ui/controls/word_list_property.cpp
    src/ui/dialogs/about_dlg_ex.cpp
    src/ui/dialogs/custom_test_dlg.cpp
    src/ui/dialogs/doc_group_select_dlg.cpp
    src/ui/dialogs/edit_text_dlg.cpp
    src/ui/dialogs/edit_word_list_dlg.cpp
    src/ui/dialogs/export_all_dlg.cpp
    src/ui/dialogs/filtered_text_export_options_dlg.cpp
    src/ui/dialogs/filtered_text_preview_dlg.cpp
    src/ui/dialogs/lua_editor_dlg.cpp
    src/ui/dialogs/new_custom_test_simple_dlg.cpp
    src/ui/dialogs/project_wizard_dlg.cpp
    src/ui/dialogs/test_bundle_dlg.cpp
    src/ui/dialogs/tools_options_dlg.cpp
    src/ui/dialogs/web_harvester_dlg.cpp
    src/ui/dialogs/word_list_dlg.cpp
    src/webharvester/filepathresolver.cpp
    src/webharvester/webharvester.cpp
    src/Wisteria-Dataviz/src/base/axis.cpp
    src/Wisteria-Dataviz/src/base/canvas.cpp
    src/Wisteria-Dataviz/src/base/colorbrewer.cpp
    src/Wisteria-Dataviz/src/base/colors.cpp
    src/Wisteria-Dataviz/src/base/commonaxisbuilder.cpp
    src/Wisteria-Dataviz/src/base/fillableshape.cpp
    src/Wisteria-Dataviz/src/base/graphitems.cpp
    src/Wisteria-Dataviz/src/base/image.cpp
    src/Wisteria-Dataviz/src/base/label.cpp
    src/Wisteria-Dataviz/src/base/lines.cpp
    src/Wisteria-Dataviz/src/base/points.cpp
    src/Wisteria-Dataviz/src/base/polygon.cpp
    src/Wisteria-Dataviz/src/base/reportbuildercolors.cpp
    src/Wisteria-Dataviz/src/base/reportprintout.cpp
    src/Wisteria-Dataviz/src/base/shapes.cpp
    src/Wisteria-Dataviz/src/data/dataset.cpp
    src/Wisteria-Dataviz/src/data/excelreader.cpp
    src/Wisteria-Dataviz/src/debug/debug_profile.cpp
    src/Wisteria-Dataviz/src/easyexif/exif.cpp
    src/Wisteria-Dataviz/src/graphs/barchart.cpp
    src/Wisteria-Dataviz/src/graphs/boxplot.cpp
    src/Wisteria-Dataviz/src/graphs/bubbleplot.cpp
    src/Wisteria-Dataviz/src/graphs/categoricalbarchart.cpp
    src/Wisteria-Dataviz/src/graphs/crawfordgraph.cpp
    src/Wisteria-Dataviz/src/graphs/danielsonbryan2plot.cpp
    src/Wisteria-Dataviz/src/graphs/fleschchart.cpp
    src/Wisteria-Dataviz/src/graphs/graph2d.cpp
    src/Wisteria-Dataviz/src/graphs/groupgraph2d.cpp
    src/Wisteria-Dataviz/src/graphs/heatmap.cpp
    src/Wisteria-Dataviz/src/graphs/histogram.cpp
    src/Wisteria-Dataviz/src/graphs/inflesz.cpp
    src/Wisteria-Dataviz/src/graphs/lineplot.cpp
    src/Wisteria-Dataviz/src/graphs/lixgauge.cpp
    src/Wisteria-Dataviz/src/graphs/lixgaugegerman.cpp
    src/Wisteria-Dataviz/src/graphs/piechart.cpp
    src/Wisteria-Dataviz/src/graphs/scalechart.cpp
    src/Wisteria-Dataviz/src/graphs/scatterplot.cpp
    src/Wisteria-Dataviz/src/graphs/wordcloud.cpp
    src/Wisteria-Dataviz/src/import/cpp_extract_text.cpp
    src/Wisteria-Dataviz/src/import/doc_extract_text.cpp
    src/Wisteria-Dataviz/src/import/docx_extract_text.cpp
    src/Wisteria-Dataviz/src/import/html_extract_text.cpp
    src/Wisteria-Dataviz/src/import/markdown_extract_text.cpp
    src/Wisteria-Dataviz/src/import/odt_odp_extract_text.cpp
    src/Wisteria-Dataviz/src/import/postscript_extract_text.cpp
    src/Wisteria-Dataviz/src/import/rtf_extract_text.cpp
    src/Wisteria-Dataviz/src/import/xlsx_extract_text.cpp
    src/Wisteria-Dataviz/src/ui/app.cpp
    src/Wisteria-Dataviz/src/ui/controls/codeeditor.cpp
    src/Wisteria-Dataviz/src/ui/controls/formattedtextctrl.cpp
    src/Wisteria-Dataviz/src/ui/controls/gtk/gtktextview-helper.cpp
    src/Wisteria-Dataviz/src/ui/controls/htmltablewin.cpp
    src/Wisteria-Dataviz/src/ui/controls/htmltablewinprintout.cpp
    src/Wisteria-Dataviz/src/ui/controls/listctrlex.cpp
    src/Wisteria-Dataviz/src/ui/controls/listctrlexdataprovider.cpp
    src/Wisteria-Dataviz/src/ui/controls/searchpanel.cpp
    src/Wisteria-Dataviz/src/ui/controls/sidebar.cpp
    src/Wisteria-Dataviz/src/ui/controls/sidebarbook.cpp
    src/Wisteria-Dataviz/src/ui/controls/thumbnail.cpp
    src/Wisteria-Dataviz/src/ui/dialogs/archivedlg.cpp
    src/Wisteria-Dataviz/src/ui/dialogs/excelpreviewdlg.cpp
    src/Wisteria-Dataviz/src/ui/dialogs/filelistdlg.cpp
    src/Wisteria-Dataviz/src/ui/dialogs/functionbrowserdlg.cpp
    src/Wisteria-Dataviz/src/ui/dialogs/getdirdlg.cpp
    src/Wisteria-Dataviz/src/ui/dialogs/gridexportdlg.cpp
    src/Wisteria-Dataviz/src/ui/dialogs/htmltablepanel.cpp
    src/Wisteria-Dataviz/src/ui/dialogs/imageexportdlg.cpp
    src/Wisteria-Dataviz/src/ui/dialogs/imagemergedlg.cpp
    src/Wisteria-Dataviz/src/ui/dialogs/listctrlitemviewdlg.cpp
    src/Wisteria-Dataviz/src/ui/dialogs/listctrlsortdlg.cpp
    src/Wisteria-Dataviz/src/ui/dialogs/listdlg.cpp
    src/Wisteria-Dataviz/src/ui/dialogs/opacitydlg.cpp
    src/Wisteria-Dataviz/src/ui/dialogs/printerheaderfooterdlg.cpp
    src/Wisteria-Dataviz/src/ui/dialogs/radioboxdlg.cpp
    src/Wisteria-Dataviz/src/ui/dialogs/warningmessagesdlg.cpp
    src/Wisteria-Dataviz/src/ui/mainframe.cpp
    src/Wisteria-Dataviz/src/util/downloadfile.cpp
    src/Wisteria-Dataviz/src/util/fileutil.cpp
    src/Wisteria-Dataviz/src/util/formulaformat.cpp
    src/Wisteria-Dataviz/src/util/hardwareinfo.cpp
    src/Wisteria-Dataviz/src/util/i18n_string_util.cpp
    src/Wisteria-Dataviz/src/util/idhelpers.cpp
    src/Wisteria-Dataviz/src/util/logfile.cpp
    src/Wisteria-Dataviz/src/util/memorymappedfile.cpp
    src/Wisteria-Dataviz/src/util/resource_manager.cpp
    src/Wisteria-Dataviz/src/util/screenshot.cpp
    src/Wisteria-Dataviz/src/util/textreplace.cpp
    src/Wisteria-Dataviz/src/util/textstream.cpp
    src/Wisteria-Dataviz/src/util/warningmanager.cpp
    src/Wisteria-Dataviz/src/util/xml_format.cpp
    src/Wisteria-Dataviz/src/util/zipcatalog.cpp
    src/Wisteria-Dataviz/src/wxStartPage/startpage.cpp)