menus/contextmenu.xrc
menus/menu.xrc
ribbon/add.svg
ribbon/adult.svg
ribbon/aggressive-list.svg
ribbon/align-center.svg
ribbon/align-left.svg
ribbon/align-right.svg
ribbon/app-logo.svg
ribbon/apple.svg
ribbon/archive.svg
ribbon/axis-orientation.svg
ribbon/bar-bottom-to-top.svg
ribbon/bar-chart.svg
ribbon/bar-glass.svg
ribbon/bar-labels.svg
ribbon/bar-left-to-right.svg
ribbon/bar-right-to-left.svg
ribbon/bar-solid.svg
ribbon/bar-sort-ascending.svg
ribbon/bar-sort-descending.svg
ribbon/bar-sort.svg
ribbon/bar-top-to-bottom.svg
ribbon/blank-graphs.svg
ribbon/blank-lines.svg
ribbon/bottom-titles.svg
ribbon/boxplot.svg
ribbon/brush.svg
ribbon/bullet-dark.svg
ribbon/bullet.svg
ribbon/bundles.svg
ribbon/capital-letter.svg
ribbon/cdc-femaledoc.svg
ribbon/chapter-split.svg
ribbon/check.svg
ribbon/checklist.svg
ribbon/citation.svg
ribbon/clear.svg
ribbon/clock.svg
ribbon/color-wheel.svg
ribbon/comment.svg
ribbon/configure.svg
ribbon/copy.svg
ribbon/cut.svg
ribbon/delete-document.svg
ribbon/delete.svg
ribbon/dev-tools.svg
ribbon/difficult.svg
ribbon/document-structure.svg
ribbon/document.svg
ribbon/documents.svg
ribbon/donut-subgrouped.svg
ribbon/down-arrow.svg
ribbon/duplicate-files.svg
ribbon/duplicate-line.svg
ribbon/edit-document.svg
ribbon/edit-report.svg
ribbon/edit.svg
ribbon/education.svg
ribbon/electronic-help.svg
ribbon/esl.svg
ribbon/examples.svg
ribbon/exclude-selected.svg
ribbon/exclusion-list.svg
ribbon/exclusion-tags.svg
ribbon/export-all.svg
ribbon/file-open.svg
ribbon/file-save.svg
ribbon/filter.svg
ribbon/find-replace.svg
ribbon/find.svg
ribbon/flesch-line.svg
ribbon/font.svg
ribbon/formula.svg
ribbon/function-dark.svg
ribbon/function.svg
ribbon/gears.svg
ribbon/german2english.svg
ribbon/go-to-line.svg
ribbon/grade-display.svg
ribbon/grammar.svg
ribbon/group.svg
ribbon/heatmap.svg
ribbon/help-button.svg
ribbon/help.svg
ribbon/highlightedwords.svg
ribbon/highlighter.svg
ribbon/highlighting.svg
ribbon/histogram.svg
ribbon/home-dark-mode.svg
ribbon/home.svg
ribbon/ignore-copyright.svg
ribbon/ignore-numerals.svg
ribbon/image.svg
ribbon/indenting.svg
ribbon/internet.svg
ribbon/invalid-region.svg
ribbon/justified.svg
ribbon/keyboard-shortcuts.svg
ribbon/ladybug.svg
ribbon/left-titles.svg
ribbon/line-spacing.svg
ribbon/link.svg
ribbon/list.svg
ribbon/log-book.svg
ribbon/logo.svg
ribbon/long-sentence.svg
ribbon/lua-dark-mode.svg
ribbon/lua.svg
ribbon/misspellings.svg
ribbon/notepad.svg
ribbon/number-syllabize.svg
ribbon/opacity.svg
ribbon/outreach.svg
ribbon/paper-notes.svg
ribbon/paragraph-indent.svg
ribbon/paragraph.svg
ribbon/paste.svg
ribbon/period-needed.svg
ribbon/person.svg
ribbon/photos-merge.svg
ribbon/photos.svg
ribbon/preview.svg
ribbon/print-header-footer.svg
ribbon/print-setup.svg
ribbon/print.svg
ribbon/project-settings.svg
ribbon/proofreading-delete.svg
ribbon/raygor-style.svg
ribbon/realtime.svg
ribbon/redo.svg
ribbon/reload.svg
ribbon/report.svg
ribbon/right-titles.svg
ribbon/run.svg
ribbon/scores-window.svg
ribbon/secondary.svg
ribbon/select-all.svg
ribbon/send-to-subproject.svg
ribbon/sentences.svg
ribbon/shadow.svg
ribbon/show-all-labels.svg
ribbon/show-all-points.svg
ribbon/showcase.svg
ribbon/sort.svg
ribbon/spreadsheet.svg
ribbon/stats.svg
ribbon/stop.svg
ribbon/sum.svg
ribbon/support.svg
ribbon/system-admin.svg
ribbon/tests-overview.svg
ribbon/toggle-sidebar.svg
ribbon/top-titles.svg
ribbon/uncomment.svg
ribbon/undo.svg
ribbon/up-arrow.svg
ribbon/updates.svg
ribbon/view-spreadsheet-item.svg
ribbon/warning.svg
ribbon/watermark.svg
ribbon/web-export.svg
ribbon/word-cloud.svg
ribbon/words.svg
ribbon/x-axis.svg
ribbon/y-axis.svg
ribbon/zoom-in.svg
ribbon/zoom-out.svg
ribbon/zoom-to-fit.svg
splash/splashscreen1.jpg
splash/splashscreen2.jpg
splash/splashscreen3.jpg
splash/splashscreen4.jpg
splash/splashscreen5.jpg
splash/splashscreen6.jpg
splash/splashscreen7.jpg
tests/amstad.svg
tests/ari-test.svg
tests/bormuth-cloze-mean-machine-passage.svg
tests/bormuth-grade-placement-35-machine-passage.svg
tests/coleman-liau-test.svg
tests/crawford.svg
tests/dale-chall-test.svg
tests/danielson-bryan-1.svg
tests/danielson-bryan-2.svg
tests/degrees-of-reading-power-grade-equivalent.svg
tests/degrees-of-reading-power.svg
tests/dolch.svg
tests/easy-listening-formula.svg
tests/eflaw-test.svg
tests/farr-jenkins-paterson.svg
tests/flesch-kincaid-test-simplified.svg
tests/flesch-kincaid-test.svg
tests/flesch-test.svg
tests/forcast-test.svg
tests/frase.svg
tests/fry-test.svg
tests/gilliam-pena-mountain-fry-graph.svg
tests/gunning-fog-test.svg
tests/harris-jacobson.svg
tests/inflesz-test.svg
tests/lix-german-childrens-literature.svg
tests/lix-german-technical.svg
tests/lix-test.svg
tests/modified-smog.svg
tests/neue-wiener-sachtextformel1.svg
tests/neue-wiener-sachtextformel2.svg
tests/neue-wiener-sachtextformel3.svg
tests/new-ari-simplified.svg
tests/new-ari.svg
tests/new-farr-jenkins-paterson.svg
tests/new-fog-count-test.svg
tests/psk-dale-chall.svg
tests/psk-farr-jenkins-paterson.svg
tests/psk-fog.svg
tests/psk-test.svg
tests/qu-bamberger-vanecek.svg
tests/raygor-test.svg
tests/rix-german-fiction.svg
tests/rix-german-nonfiction.svg
tests/rix-test.svg
tests/schwartz.svg
tests/smog-bamberger-vanecek.svg
tests/smog-test-simplified.svg
tests/smog-test.svg
tests/sol-spanish.svg
tests/spache-test.svg
tests/stocker.svg
tests/wheeler-smith-bamberger-vanecek.svg
tests/wheeler-smith.svg
wizard/centered-text.png
wizard/hard-returns.png
wizard/line-ends-are-new-paragraphs.png
wizard/narrative-illustrated.png
wizard/narrative-text.png
wizard/narrative-with-lines.png
wizard/sparse-text.png