abbreviations/abbreviations.txt
abbreviations/non-abbreviations.txt
articles/a-exceptions.txt
articles/an-exceptions.txt
caption-labels/captions.txt
citation-headers/citations.txt
copyright-notices/notices.txt
dictionaries/english.txt
dictionaries/german.txt
dictionaries/spanish.txt
past-participles/exceptions.txt
programming/all-languages.txt
proper-nouns/all.txt
proper-nouns/personal.txt
stop-words/english.txt
stop-words/german.txt
stop-words/proper-nouns-stoplist.txt
stop-words/spanish.txt
word-lists/dolch.txt
word-lists/harris-jacobson.txt
word-lists/new-dale-chall.txt
word-lists/revised-spache.txt
word-lists/stocker-catholic-supplement.txt
wordy-phrases/dale-chall-replacements.txt
wordy-phrases/english.txt
wordy-phrases/german.txt
wordy-phrases/harris-jacobson-replacements.txt
wordy-phrases/single-word-replacements-english.txt
wordy-phrases/spache-replacements.txt
wordy-phrases/spanish.txt