```{r}
#| include: false
#| eval: true

source('../R/appdown.r')
```

::: {.content-hidden when-profile="cheatsheet"}
# Keyboard Shortcuts
:::

::: {.content-visible when-profile="cheatsheet"}
# *{{< var PROGRAM_NAME >}}* Keyboard Shortcuts {.unnumbered}
:::

<!-- no break spaces are to add blank lines between each row in the shortcuts table,
     making it easier to read.-->

::: {.minipage data-latex="{\textwidth}"}
Table: Application

------------------------------------------------------------------------------------------------
To do this                              Press                                               
--------------------------------------- --------------------------------------------------------
Open the help                           `r keys('F1')`

&nbsp;                                  &nbsp;

Enable verbose logging                  Hold down `r keys('Shift')` (`r os_logo('windows')`, `r os_logo('linux')`) or
                                        `r keys('\\shift')` (`r os_logo('apple')`)<br>\linebreak
                                        while the program loads
------------------------------------------------------------------------------------------------
:::

::: {.minipage data-latex="{\textwidth}"}
Table: Projects

------------------------------------------------------------------------------------------------
To do this                              Press                                               
--------------------------------------- --------------------------------------------------------
Show/hide the sidebar                   `r keys('F2')`                                          

&nbsp;                                  &nbsp;

Show/hide the ribbon                    `r keys('F4')`

&nbsp;                                  &nbsp;

Reload the project                      `r keys('F5')`

&nbsp;                                  &nbsp;

Create a new project                    `r keys(c('Ctrl','V'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','V'))` (`r os_logo('apple')`) 

&nbsp;                                  &nbsp;

Save the project                        `r keys(c('Ctrl','S'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','S'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Print the active window                 `r keys(c('Ctrl','P'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','P'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Remove the selected test                `r keys(c('Ctrl', 'Del'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','\\backdel'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Edit/view the selected document         `r keys('F6')`

&nbsp;                                  &nbsp;

Create subproject<br>\linebreak         `r keys(c('Ctrl','\\arrowkeyright'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
(batch projects only)                   `r keys(c('\\cmd','\\arrowkeyright'))` (`r os_logo('apple')`)
------------------------------------------------------------------------------------------------
:::

::: {.minipage data-latex="{\textwidth}"}
Table: Graphs

------------------------------------------------------------------------------------------------
To do this                              Press                                               
--------------------------------------- --------------------------------------------------------
Print                                   `r keys(c('Ctrl','P'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','P'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Copy                                    `r keys(c('Ctrl','C'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','C'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Zoom in                                 `r keys('{+}')`                                     

&nbsp;                                  &nbsp;

Zoom out                                `r keys('-')`                                       

&nbsp;                                  &nbsp;

Reset zoom                              `r keys('*')`                                       
------------------------------------------------------------------------------------------------
:::

::: {.minipage data-latex="{\textwidth}"}
Table: Lists

------------------------------------------------------------------------------------------------
To do this                              Press                                               
--------------------------------------- --------------------------------------------------------
Print                                   `r keys(c('Ctrl','P'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','P'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Copy selection                          `r keys(c('Ctrl','C'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','C'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Copy first column of selection          `r keys(c('Ctrl','Shift','C'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','\\shift','C'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Copy column from selection<br>\linebreak     `r keys(c('Ctrl','Numpad [1–9]'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
(column corresponds to the number)           `r keys(c('\\cmd','Numpad [1–9]'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Find                                    `r keys(c('Ctrl','F'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','F'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Find next                               `r keys('F3')`

&nbsp;                                  &nbsp;

Select all                              `r keys(c('Ctrl','A'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','A'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Go to first item                        `r keys(c('Ctrl','\\arrowkeyup'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','\\arrowkeyup'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Go to last item                         `r keys(c('Ctrl','\\arrowkeydown'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','\\arrowkeydown'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Remove selected item(s)                 `r keys('Del')` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys('\\backdel')` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Edit selected item                      `r keys('F2')`

&nbsp;                                  &nbsp;

Accept edited item                      `r keys('Enter')`, `r keys('Tab')`, `r keys('\\arrowkeyup')`, `r keys('\\arrowkeydown')` (or mouse click outside the edit box)

&nbsp;                                  &nbsp;

Cancel editing item                     `r keys('Esc')`

&nbsp;                                  &nbsp;

Add an item                             `r keys(c('Ctrl','Ins'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','Ins'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Group selected items<br>\linebreak      `r keys(c('Ctrl','G'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
(batch project wizard file list)        `r keys(c('\\cmd','G'))` (`r os_logo('apple')`)
------------------------------------------------------------------------------------------------
:::

::: {.minipage data-latex="{\textwidth}"}
Table: Script Editor

------------------------------------------------------------------------------------------------
To do this                              Press                                               
--------------------------------------- --------------------------------------------------------
Create a new script                     `r keys(c('Ctrl','Shift','N'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','\\shift','N'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Open a script                           `r keys(c('Ctrl','Shift','O'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','\\shift','O'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Save the script                         `r keys(c('Ctrl','Shift','S'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','\\shift','S'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Run selection<br>\linebreak             `r keys('F5')`
(or full script if no selection);<br>\linebreak
also continues execution when
paused at a breakpoint

&nbsp;                                  &nbsp;

Stop running                            `r keys(c('Shift','F5'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\shift','F5'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Toggle breakpoint on the                `r keys('F9')`
current line

&nbsp;                                  &nbsp;

Cut selected text                       `r keys(c('Ctrl','X'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','X'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Paste text                              `r keys(c('Ctrl','V'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','V'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Copy selected text                      `r keys(c('Ctrl','C'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','C'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Undo previous edit                      `r keys(c('Ctrl','Z'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','Z'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Redo previous edit                      `r keys(c('Ctrl','Y'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','Y'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Find                                    `r keys(c('Ctrl','F'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','F'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Find next                               `r keys('F3')`

&nbsp;                                  &nbsp;

Replace                                 `r keys(c('Ctrl','H'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','H'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Select all                              `r keys(c('Ctrl','A'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','A'))` (`r os_logo('apple')`)
                                        

&nbsp;                                  &nbsp;

Duplicate current line                  `r keys(c('Ctrl','D'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','D'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Go to line                              `r keys(c('Ctrl','G'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','G'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Comment/uncomment selection             `r keys(c('Ctrl','/'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','/'))` (`r os_logo('apple')`)
------------------------------------------------------------------------------------------------
:::

::: {.minipage data-latex="{\textwidth}"}
Table: Embedded Document Editor

------------------------------------------------------------------------------------------------
To do this                              Press                                               
--------------------------------------- --------------------------------------------------------
Save back to the project                `r keys(c('Ctrl','S'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','S'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Cut selected text                       `r keys(c('Ctrl','X'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','X'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Paste text                              `r keys(c('Ctrl','V'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','V'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Copy selected text                      `r keys(c('Ctrl','C'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','C'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Undo previous edit                      `r keys(c('Ctrl','Z'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','Z'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Redo previous edit                      `r keys(c('Ctrl','Y'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','Y'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Insert date                             `r keys(c('Ctrl',';'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd',';'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Insert time                             `r keys(c('Ctrl','Shift',';'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','\\shift',';'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Find                                    `r keys(c('Ctrl','F'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','F'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Find next                               `r keys('F3')`

&nbsp;                                  &nbsp;

Replace                                 `r keys(c('Ctrl','H'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','H'))` (`r os_logo('apple')`)

&nbsp;                                  &nbsp;

Select all                              `r keys(c('Ctrl','A'))` (`r os_logo('windows')`, `r os_logo('linux')`) or<br>\linebreak
                                        `r keys(c('\\cmd','A'))` (`r os_logo('apple')`)
------------------------------------------------------------------------------------------------
:::

::: {.minipage data-latex="{\textwidth}"}
Table: Web Harvester

------------------------------------------------------------------------------------------------
To do this                              Press                                               
--------------------------------------- --------------------------------------------------------
Load links from HTML content            `r keys(c('Ctrl','K'))` (`r os_logo('windows')`) or<br>\linebreak
                                        `r keys(c('\\cmd','K'))` (`r os_logo('apple')`)
------------------------------------------------------------------------------------------------
:::
