```{r}
#| include: false
#| eval: true

source('R/appdown.r')
```

# Getting Involved

All are welcome to get involved with *{{< var PROGRAM_NAME >}}* by contributing to the code, documentation, word list, artwork, or simply by sharing feedback and ideas.

There are two main ways to get involved: reporting issues or requests and contributing changes.

## Report a Bug or Request a Feature {-}

If you encounter a problem or have an idea for improvement, please visit our issue tracker:

- **Issue Tracker:** [{{< var ISSUE_PAGE >}}]({{< var ISSUE_PAGE >}})

When opening an issue:

- Bug reports should clearly describe:
  - What happened
  - What you expected to happen
  - Steps to reproduce the problem (if applicable)
  - Screenshots or examples, if helpful
- Feature requests should describe:
  - The problem you're trying to solve
  - The solution you'd like to see
  - Any alternatives you've considered

To report an issue, a *GitHub* account is required.
Creating a *GitHub* account is free and only takes a few minutes.

::: {.warningsection data-latex=""}
All issues are public.
Please do not include sensitive or confidential information.
:::

{{< pagebreak >}}

## Contribute Code, Documentation, or Other Assets {-}

If you would like to contribute code, documentation, translations, word lists, artwork, or other project assets, follow these steps to become a contributor:

- Register with *GitHub*\
  Go to [GitHub.com](https://github.com/) and click **Sign up** in the upper right corner to create a free account.
- Register with *Eclipse*\
  Go to [Eclipse.org](https://www.eclipse.org/) and click **Create account** in the upper right corner to create a free account.
- Connect *Eclipse* and *GitHub*\
  Once your accounts are set up, select **Edit my account** in the upper right corner of *Eclipse.org*.
  On the **My Account** page, select the **Account Settings** tab.
  Enter the name of your *GitHub* account in the **GitHub ID** field and click **Update Account**.
- Digitally Sign the Eclipse ECA\
  While still on the **My Account** page, go to the **Eclipse ECA** tab and follow the instructions to sign the Eclipse Contributor Agreement.
  This certifies that your contributions are legally yours to contribute and will be made available under an open source license.

To make a contribution:

- Create a fork of our repository at [{{< var GIT_REPO >}}]({{< var GIT_REPO >}}) and make your edits to this fork.
- Submit your changes as a pull request.
- After review and approval, your contribution will be merged into the program.

While preparing your contributions, please follow our coding and technical writing style guidelines, as outlined in this chapter.
