```{r}
#| include: false
#| eval: true

source('R/appdown.r')
```

# Linux `r os_logo('linux')`

Install the following tools to build *{{< var PROGRAM_NAME >}}*:

| Program |
| :-- |
| *GCC* {{< var MIN_GCC_REQUIRED >}} or higher (*gcc* and *gfortran*) |
| *CMake* {{< var CMAKE_MINIMUM_REQUIRED_VERSION >}} or higher (*cmake* and *cmake-extra*) |
| *git* |
| *AppImage* (*libappimage-dev*) |
| *R* (*r-base*, optional) |
| *Quarto* ([https://quarto.org/](https://quarto.org/), optional) |
| *POEdit* (*poedit*, optional) |

Install the following libraries:

| Library | Debian / Ubuntu | RHEL / Fedora / openSUSE |
| :-- | :-- | :-- |
| *GTK 3* | *libgtk-3-dev* | *gtk3-devel* |
| *libcurl* | *libcurl4-openssl-dev* | *libcurl-devel* |
| *GStreamer MM* | *libgstreamermm-1.0-dev* | *gstreamermm-devel* |
| *libsecret* | *libsecret-1-dev* | *libsecret-devel* |
| *WebKitGTK* | *libwebkit2gtk-4.1-dev* | *webkit2gtk3-devel* |
| *SDL2* | *libsdl2-dev* | *SDL2-devel* |
| *libnotify* | *libnotify-dev* | *libnotify-devel* |
| *TBB* | *libtbb-dev* | *tbb-devel* |
| *OpenSSL* | *libssl-dev* | *openssl-devel* |
| *libxml2* | *libxml2-dev* | *libxml2-devel* |
| *gspell* | *libgspell-1-dev* | *gspell-devel* |
| *ImageMagick++* (optional) | *libmagick++-dev* | *ImageMagick-c++-devel* |
| *Poppler* (optional) | *libpoppler-cpp-dev* | *poppler-cpp-devel* |

{{< pagebreak >}}

## Download *wxWidgets* {-}

```{.bash}
git clone https://github.com/wxWidgets/wxWidgets.git --recurse-submodules
```

This should be cloned into a folder next to *{{< var PROGRAM_NAME >}}*.

## Build *{{< var PROGRAM_NAME >}}* {-}

```{.bash include="build-commands.txt" start-line=1 end-line=9}
```

::: {.tipsection data-latex=""}
To create a debug build, pass `-DCMAKE_BUILD_TYPE=Debug` during the configuration stage, and `--config Debug` during the build stage.
You can also pass `-DENABLE_SANITIZERS=TRUE` to enable AddressSanitizer support in debug builds.

If you need to build with local modifications in Git submodules, add `-DALLOW_DIRTY_SUBMODULES=ON` to bypass the clean-check validation.
:::

## Build the AppImage {-}

::: {.tipsection data-latex=""}
The following steps are only required if you are distributing builds outside CI, your local machine, or Eclipse's infrastructure.
:::

```{.bash}
linuxdeploy-x86_64.AppImage --appdir installers/unix/AppDir \
  --executable installers/unix/AppDir/usr/bin/readstudio    \
  -d installers/unix/AppDir/readstudio.desktop              \
  -i installers/unix/AppDir/app-logo.svg                    \
  --output appimage
mv Readability_Studio*.AppImage ./installers/unix
```

Once built, the AppImage will be available in `r menu(c('installers', 'unix'))`.
Apply a GPG signature to it before distributing.
