```{r}
#| include: false
#| eval: true

source('R/appdown.r')
```

# Linux `r os_logo('linux')`

| Requirements |
| :-- |
| x86_64 processor |
| {{< var INSTALLED_SIZE_MB >}} MB of disk space |
| {{< var MIN_RAM >}} of RAM ({{< var RAM_RECOMMENDED >}} recommended) |

## AppImage {-}

### Installing {-}

Make "Readability_Studio-{{< var UNIX_ARCHITECTURE >}}.AppImage" executable.
This can be done with the following syntax:

```{.bash}
chmod u+x <AppImage File>
```

This can also be done by right-clicking the file, selecting `r menu(c('Properties', 'Permissions'))` and checking *Allow executing file as program*.

This only needs to be done once.
Now "Readability_Studio-{{< var UNIX_ARCHITECTURE >}}.AppImage" can be run directly to launch the program.

::: {.notesection data-latex=""}
An AppImage is a portable Linux app with all dependencies included, ready to run without installation.
:::

### Uninstalling {-}

Drag "Readability_Studio-{{< var UNIX_ARCHITECTURE >}}.AppImage" into the Trash.

### Updating {-}

Replace your existing AppImage with the latest version.
Make the new AppImage executable and then it will be ready to run.

## DEB Package {-}

### Installing {-}

Install "readstudio_{{< var FULL_VERSION >}}_amd64.deb" from the command line:

```{.bash}
sudo apt install ./readstudio_{{< var FULL_VERSION >}}_amd64.deb
```

This will also resolve and install any missing dependencies.

::: {.notesection data-latex=""}
Alternatively, `dpkg -i` can be used, followed by `sudo apt-get install -f` to resolve any missing dependencies.
:::

The DEB package can also be installed interactively.
Double-click it to open it in the distribution's graphical package installer (e.g., *GNOME Software* or *Software Install*).
From there, click **Install** and provide your password when prompted.

### Uninstalling {-}

```{.bash}
sudo apt remove readstudio
```

### Updating {-}

Install the newer DEB package the same way as the initial installation; this will upgrade the existing installation.
