```{r}
#| include: false
#| eval: true

source('R/appdown.r')
```

# Telemetry

*{{< var PROGRAM_NAME >}}* does not transmit or share user information.
If a user needs to share usage information generated by the program, they must do it explicitly.

The program does not require an internet connection, except for when users instruct it to analyze or download webpages.
*{{< var PROGRAM_NAME >}}* does not "phone home" and does not need an internet connection if analyzing local (or network) documents.

## Log File {-}

While it is running, *{{< var PROGRAM_NAME >}}* logs various diagnostic information.
This information can provide details such as:

- The location of where the program is loading its license and settings files
- Parsing errors encountered while reading documents (e.g., malformed HTML files)
- Warnings and errors encountered while performing analyses
- The paths of documents being analyzed (verbose mode only)
- Information about the operating system (e.g., OS version, default font, etc.)
- Version information about various libraries used by the program

Except for file paths, no personal identifying information (PII) is recorded.

This information is only saved to a file in the user's local temp folder.
It is not transmitted to any external service and is only intended for diagnosing issues with the software.
This file can be optionally included in crash reports generated by the program.
These crash reports must, however, be explicitly sent to the vendor by the user.

::: {.tipsection data-latex=""}
To view this log report, go to the **Tools** tab on the ribbon, then click **Log Report** under the **Tools & Settings** section.
From the **Log Report** dialog, you can review, save, and print this information.
:::

## Connectivity {-}

*{{< var PROGRAM_NAME >}}* only connects to the internet when it is instructed by the user to analyze or download a webpage.

The program has two interfaces for internet connectivity.
The first is that it can analyze a webpage provided by the user.
The second is its **Web Harvester** feature, which can crawl a user-provided website, where it will read and download its links.
When connecting to these websites, the program will only send basic page request information; user's personal information is not transmitted.
