```{r}
#| include: false
#| eval: true

source('R/appdown.r')
```

# Microsoft^®^ Windows `r os_logo('Windows')`

| Install the following tools to build *{{< var PROGRAM_NAME >}}* |
| :-- |
| *Visual Studio {{< var MIN_MSVC_REQUIRED >}}* or higher |
| *Inno Setup* |
| *R* from CRAN (optional) |
| *Quarto* (optional) |
| *POEdit* (optional) |

{{< pagebreak >}}

## Download *wxWidgets* {-}

- Open *Visual Studio* and select **Clone a Repository**
  - Enter ["https://github.com/wxWidgets/wxWidgets.git"](https://github.com/wxWidgets/wxWidgets.git) and clone (i.e., download) it

## Build *{{< var PROGRAM_NAME >}}* {-}

- From *Visual Studio*, select **Clone a Repository** again
  - Enter ["{{< var GIT_REPO >}}.git"]({{< var GIT_REPO >}}.git) and clone it to the same level as the "wxWidgets" folder
- Once the "ReadabilityStudio" folder is cloned, open it in *Visual Studio*
- Select the "Visual Studio {{< var MIN_MSVC_REQUIRED >}} Release" configuration and build it
- Optionally, the "manuals" target can also be ran to rebuild the documentation

::: {.tipsection data-latex=""}
To create a debug build, select the "Visual Studio {{< var MIN_MSVC_REQUIRED >}} Debug" configuration.
Additionally, selecting "Visual Studio {{< var MIN_MSVC_REQUIRED >}} Debug w/ ASAN" will enable AddressSanitizer.

To allow building with uncommitted changes in Git submodules, open your "CMakePresets.json" file and add the following to your chosen profile:

```json
"cacheVariables": {
  "ALLOW_DIRTY_SUBMODULES": "ON"
}
```
:::

## Build the installer {-}

::: {.tipsection data-latex=""}
The following steps are only required if you are distributing builds outside CI, your local machine, or Eclipse's infrastructure.
:::

::: {.notesection data-latex=""}
If you build the "Release" version of *{{< var PROGRAM_NAME >}}*, then the *CMake* build process will copy "{{< var BUILD_TARGET >}}.exe" into `r menu(c('installers', 'windows', 'release'))`.
:::

- Go to `r menu(c('installers', 'windows'))`
- Digitally sign "release/{{< var BUILD_TARGET >}}.exe"
- Open "{{< var BUILD_TARGET >}}.iss" in *Inno Setup* and build the installer
  - The installer will be placed in "output/rssetup{{< var FULL_VERSION >}}.exe"
- Digitally sign the installer
