## Automated Readability Index\index{Automated Readability Index|(idxit} {#sec-ari-test}

The Automated Readability Index–also called "ARI" or "auto"–[@{esmith}] was originally created for U.S. Air Force materials.
As such, it was designed for technical reports and manuals.
This test calculates the grade level of a document based on sentence length and character count.

Kincaid et al. [-@{kincaid:1972}3, 6–15] also used this test for evaluating peer-prepared reading materials for three studies involving:

- 33 remedial high school students
- 22 graduate students from Southern Georgia College
- 14 trainees participating in a Public Service Careers project at Southern Georgia College

They noted that for the high school study, the materials with lower ARI scores yielded better comprehension rates "as reflected in cloze scores" [-@{kincaid:1972}3].
The graduate students and trainees from the other studies stated that the materials may not be appropriate for remedial high school readers [-@{kincaid:1972}13, 15], but did agree that the stories were "authentic" and "interesting."

::: {.callout-note icon=false}
## ARI formula

$$
G = (4.71 * (RP/W)) + (0.5 * (W/S)) - 21.43
$$
:::

Where:

```{r, echo=F}
ariData <- tibble(col1 = c("G", "W", "RP", "S"),
                  col2 = markdown_to_kable_cell(c("Grade level",
                                    "Number of words",
                                    "Number of strokes^a^",
                                    "Number of sentences")))

colnames(ariData) <- rep('', ncol(ariData))
kableExtra::kbl(ariData, booktabs=T, centering=T, align='l',escape=F) %>%
  kableExtra::kable_classic(full_width=F) %>%
  column_spec(2, width='10cm') %>%
  footnote(alphabet = c("Strokes are characters and punctuation (except for sentence terminating punctuation)"),
           threeparttable=T)
```
\index{Automated Readability Index|)}

\newpage