## Bormuth Grade Placement (GP35)\index{Bormuth Grade Placement|(idxit} {#sec-bormuth-grade-placement-35-machine-passage}

The Bormuth Grade Placement (Machine Computation for Passage Readability) Formula [-@{bormuth:1966}79–132] calculates a grade level for a document.

This test is influenced by three variables (word length, sentence length, and word familiarity).
Because it uses both word familiarity and syntactic complexity for its analysis, it is often recommended for student documents.

For this formula, a study involving 2,600 students ranging from 4^th^-12^th^ grade [-@{bormuth:1969}97] was conducted.
The students completed 330 110-word cloze passages, and their scores were correlated against numerous linguistic factors from the passages.
After a series of factor analyses and multiple regressions, a series of formulas were created to predict cloze and grade-level scores for a passage.
These formulas were then cross-validated against 20 250–300 word passages [-@{bormuth:1969}105].
These formulas correlated with between $r^2 = 0.81$ to $0.83$ with the original test data and between $r^2 = 0.92$ to $0.93$ with the cross validation data.

Of these formulas, the grade-placement formula is as follows:

::: {.callout-note icon=false}
## Bormuth Grade Placement formula

\begin{align*}
  G = & 3.761864 + 1.053153*(R/W) - 2.138595*(D/W)^3 + \\
      & .152832*(W/S) - .002077*(W/S)^2
\end{align*}
:::

Where:

+:----+:-------------------------------------+
| G   | Grade level                          |
+-----+--------------------------------------+
| R   | Number of characters                 |
+-----+--------------------------------------+
| W   | Number of words                      |
+-----+--------------------------------------+
| D   | Number of familiar [Dale-Chall](#sec-dale-chall-test) words |
+-----+--------------------------------------+
| S   | Number of sentences                  |
+-----+--------------------------------------+

Note that this particular grade-placement test uses the regression equation that best fit the passages with cloze scores averaging ~35%.
There are also 45% and 55% cloze-score fitting Bormuth equations, but as Bormuth noted "35 per cent on a cloze readability test tentatively seemed to represent a criterion for deciding whether or not students are able to exhibit a maximum of information gain as a consequence of reading the passage" [-@{bormuth:1969}102].\index{Bormuth Grade Placement|)}

\newpage