## Grade Level Results {#sec-grade-level-results}

Most readability tests that return a grade level include a mantissa (i.e., decimal value), which represents the month of the grade.
For example, *1.6* would be the sixth month of first grade [@{carver:1985}306–07].
However, this only applies to tests that are computed from a mathematical formula (generally, a regression equation).
Tests that use different methods—such as lookup tables or graphs—usually only return a grade level as an integer.

For example, [New Dale-Chall](#sec-dale-chall-test)\index{New Dale-Chall!calculation method} looks up your unfamiliar word and sentence counts from a table and returns a grade range.
This will yield results such as *7–8*, meaning that a document falls within the seventh to eighth grade reading level.

[Lix](#sec-lix-test)\index{Lix} and [Rix](#sec-rix-test)\index{Rix!calculation method} use a similar method.
These tests calculate an index score and then look up the grade level from a table using this value.

Finally, graphical tests (e.g., [Fry](#sec-fry-test)\index{Fry!calculation method}) only return integral grade levels because the bands on these graphs only represent the grade, not the grade and month.
