## Grade Scales {#sec-grade-scales}

Grade-level scores are traditionally displayed in U.S. (K–12+) format, but can be converted to other scales.
The following grade scales are available to choose from:

```{r, echo=F}
usaGradeScale <- read_tsv("data/USAGradeScale.txt", col_names=F)[[1]]
englishKeyStages <- read_tsv("data/EnglandWalesGradeScale.txt", col_names=F)[[1]]
```

```{r, echo=F, eval=knitr::is_html_output()}
usaGradeScale <- split_column_into_table(usaGradeScale, 15, str_glue("Grade Levels{superscript('a,b')}"))
kableExtra::kbl(usaGradeScale, booktabs=T, centering=T, linesep="",
                caption="United States of America", align='l', escape=F) %>%
  kableExtra::kable_classic(full_width=F) %>%
  kableExtra::kable_styling(position = "float_left") %>%
  footnote(alphabet = c(url('www.ed.gov/k-12reforms'), url('www.education.ohio.gov/Topics/Learning-in-Ohio')),
           escape=F, threeparttable=T)
```

```{r, echo=F, eval=knitr::is_html_output()}
englishKeyStages <- split_column_into_table(englishKeyStages, 15, str_glue("Key Stages{superscript('a,b')}"))
kableExtra::kbl(englishKeyStages, booktabs=T, centering=T, linesep="",
                caption="England and Wales", align='l', escape=F) %>%
  kableExtra::kable_classic(full_width=F) %>%
  kableExtra::kable_styling(position = "left") %>%
  footnote(alphabet = c(url('www.curriculum.qca.org.uk/index.aspx'), url('www.old.accac.org.uk/index.php')),
           escape=F, threeparttable=T)
```

```{r, echo=F, eval=knitr::is_latex_output()}
if (length(usaGradeScale) > length(englishKeyStages))
  { length(englishKeyStages) <- length(usaGradeScale) }
if (length(englishKeyStages) > length(usaGradeScale))
  { length(usaGradeScale) <- length(englishKeyStages) }
usaGradeScale <- split_column_into_table(usaGradeScale, 15, str_glue("Grade Levels{superscript('a,b')}"))
englishKeyStages <- split_column_into_table(englishKeyStages, 15, str_glue("Key Stages{superscript('a,b')}"))

usaKable <- kableExtra::kbl(usaGradeScale, booktabs=T, centering=T, linesep="",
                align='l', escape=F)
ukKable <- kableExtra::kbl(englishKeyStages, booktabs=T, centering=T, linesep="",
                align='l', escape=F)
knitr::asis_output(glue_collapse(
  c(R"(\begin{table}[!htb]
\begin{minipage}{.5\linewidth}
\captionof{table}{United States of America})",
    usaKable,
    R"(  \footnotetext{\textsuperscript{a} \url{www.ed.gov/k-12reforms}}
\footnotetext{\textsuperscript{b} \url{www.education.ohio.gov/Topics/Learning-in-Ohio}}
\hspace{1cm}
\end{minipage}%
\hspace{.1cm}
\begin{minipage}{.5\linewidth}
\captionof{table}{England and Wales})",
    ukKable,
    R"(  \footnotetext{\textsuperscript{a} \url{www.curriculum.qca.org.uk/index.aspx}}
\footnotetext{\textsuperscript{b} \url{www.old.accac.org.uk/index.php}}
\end{minipage}
\end{table})")))
```

\newpage

```{r, echo=F}
library(tidyverse)

col1Indices <- c(1,8,15,22,30,39)
col2Indices <- c(1,8,15,22,30,39)
canadaTable <- tibble(V1 = c(str_glue("K–12+ (Alberta){superscript('a')}"),
                             "Elementary (Kindergarten–grade 6)", "Junior High (grades 7–9)",
                             "Senior High (grades 10–12)", "College (grades 13–16)",
                             "Graduate School (grades 17–18)", "Doctorate (grade 19+)",

                             str_glue("K–12+ (British Columbia){superscript('b')}/Yukon{superscript('c')}"),
                             "Elementary (Kindergarten–grade 7)", "Junior Secondary (grades 8–10)",
                             "Senior Secondary (grades 11–12)", "College (grades 13–16)",
                             "Graduate School (grades 17–18)", "Doctorate (grade 19+)",

                             str_glue("K–12+ (Manitoba){superscript('d')}"),
                             "Early (Kindergarten–grade 4)",
                             "Middle (grades 5–8)",
                             "Senior (grades 9–12)",
                             "College (grades 13–16)",
                             "Graduate School (grades 17–18)",
                             "Doctorate (grade 19+)",

                             str_glue("K–12+ (New Brunswick){superscript('e')}"),
                             "Elementary (Kindergarten–grade 5)",
                             "Middle School (grades 6–8)",
                             "High School (grades 9–12)",
                             "College (grades 13–16)",
                             "Graduate School (grades 17–18)",
                             "Doctorate (grade 19+)",
                             "",

                             str_glue("K–12+ (Newfoundland {ampersand()} Labrador){superscript('f')}"),
                             "Kindergarten",
                             "Primary (grades 1–3)",
                             "Elementary (grades 4–6)",
                             "Intermediate (grades 7–9)",
                             "Senior High (Level I–III)",
                             "College (grades 13–16)",
                             "Graduate School (grades 17–18)",
                             "Doctorate (grade 19+)",

                             str_glue("K–12+ (Northwest Territories){superscript('g')}"),
                             "Primary (Kindergarten–grade 3)",
                             "Intermediate (grades 4–6)",
                             "Junior Secondary (grades 7–9)",
                             "Senior Secondary (grades 10–12)",
                             "College (grades 13–16)",
                             "Graduate School (grades 17–18)",
                             "Doctorate (grade 19+)"),

                     V2 = c(str_glue("K–12+ (Nova Scotia){superscript('h')}"),
                            "Elementary (Primary–grade 6)",
                            "Junior High (grades 7–9)",
                            "Senior High (grades 10–12)",
                            "College (grades 13–16)",
                            "Graduate School (grades 17–18)",
                            "Doctorate (grade 19+)",

                            str_glue("K–12+ (Nunavut){superscript('i')}"),
                            "Kindergarten (grade 0)",
                            "Grades 1–12",
                            "College (grades 13–16)",
                            "Graduate School (grades 17–18)",
                            "Doctorate (grade 19+)",
                            " ",

                            str_glue("K–12+ (Ontario){superscript('j')}"),
                            "Elementary (grades 1–8)",
                            "Grades 9–12",
                            "College (grades 13–16)",
                            "Graduate School (grades 17–18)",
                            "Doctorate (grade 19+)",
                            " ",

                            str_glue("K–12+ (Prince Edward Island){superscript('k')}"),
                            "Kindergarten",
                            "Elementary (grades 1–6)",
                            "Intermediate School (grades 7–9)",
                            "Senior High (grades 10–12)",
                            "College (grades 13–16)",
                            "Graduate School (grades 17–18)",
                            "Doctorate (grade 19+)",

                            str_glue("K–12+ (Saskatchewan){superscript('l')}"),
                            "Kindergarten",
                            "Elementary Level (grades 1–5)",
                            "Middle Level (grades 6–9)",
                            "Secondary Level (grades 10–12)",
                            "College (grades 13–16)",
                            "Graduate School (grades 17–18)",
                            "Doctorate (grade 19+)",
                            " ",

                            str_glue("Quebec{superscript('m')}"),
                            "Maternelle (Kindergarten)",
                            "École Primaire (grades 1–6)",
                            "École Secondaire (grades 7–11)",
                            "CEGEP (two years of university prep)",
                            "University (3 years for Bachelor's degree)",
                            "Graduate degree (2 years)",
                            "Doctoral degree")) %>%
  mutate("V1" = kableExtra::cell_spec(V1, bold = (row_number() %in% col1Indices), escape=F)) %>%
  mutate("V1" = ifelse(!(row_number() %in% col1Indices), paste0(indentation(), V1), V1)) %>%
  dplyr::rename("Grade Levels" = V1) %>%
  mutate("V2" = kableExtra::cell_spec(V2, bold = (row_number() %in% col2Indices), escape=F)) %>%
  mutate("V2" = ifelse(!(row_number() %in% col2Indices), paste0(indentation(), V2), V2)) %>%
  dplyr::rename("Grade Levels " = V2)

kableExtra::kbl(canadaTable, longtable=T, booktabs=T, centering=T, escape=F, linesep="",
                caption=str_glue("Canadian Provinces {ampersand()} Territories")) %>%
  kableExtra::kable_classic(full_width=F) %>%
  kableExtra::column_spec(1, border_right=T) %>%
  kableExtra::kable_styling(latex_options = c("repeat_header"),
                            # this can be set to TRUE once BR #742 in kableExtra is fixed
                            repeat_header_continued = F) %>%
  footnote(alphabet = c(url('www.education.alberta.ca/media/832568/guidetoed.pdf'),
                      url('www.bced.gov.bc.ca/reporting/glossary.php'),
                      url('www.education.gov.yk.ca/psb/curriculum.html'),
                      url('www.edu.gov.mb.ca/ks4/schools/gts.html'),
                      url('www.gnb.ca/0000/anglophone-e.asp'),
                      url('www.ed.gov.nl.ca/edu/sp/pcdbgl.htm'),
                      url('www.ece.gov.nt.ca/Divisions/kindergarten_g12/curriculum/Elementary_Junior_Secondary_School_Handbook/Elementary_Junior_Secondary_School_Handbook.htm'),
                      url('www.ednet.ns.ca/pdfdocs/psp/psp_03_04_full.pdf'),
                      url('www.ntanu.ca/assets/docs/Handout-Nunavut%20Approved%20Teaching%20Resources%20Version%20(5).pdf'),
                      url('www.edu.gov.on.ca/eng/educationFacts.html'),
                      url('www.edu.pe.ca/curriculum/default.asp'),
                      url('www.sasked.gov.sk.ca/branches/curr/index.shtml'),
                      url('www.ibe.unesco.org/en/access-by-country/europe-and-north-america/canada/curricular-resources.html')),
           escape=F, threeparttable=T)
```
