project:
  type: book
  output-dir: "docs"
toc: true
toc-depth: 2
biblio-title: References
bibliography: cites.bib
biblio-style: mla
link-citations: true
nocite: '@*'
csl: modern-language-association.csl
pdf-cover: "images/non-generated/api-cover.png"
pdf-cover-font-color: "255, 255, 255"
pdf-cover-author-color: "61, 60, 59"
pdf-logo: "images/non-generated/cover-logo.png"
trademark: "{{< var PROGRAM_LONGNAME >}}"
publisher: "{{< var PUBLISHER >}}"
publisher-cities:
  - Brussels
  - Ottawa
  - Darmstadt
theme-color: "248, 149, 34"
page-side-decoration-color: "61, 60, 59"
chapter-image: "non-generated/banner.jpg"
number-sections: true
crossref:
  chapters: true
fontfamilies:
  - name: \brandfont
    font: Roboto
    options:
      - Path=./fonts/Roboto/
      - Extension=.ttf
      - UprightFont=*-VariableFontwdthwght
      - ItalicFont=*-ItalicVariableFontwdthwght
  - name: \covertitlefont
    font: PlayfairDisplay
    options:
      - Path=./fonts/PlayfairDisplay/
      - Extension=.ttf
      - UprightFont=*-VariableFontwght
      - ItalicFont=*-ItalicVariableFontwght
book:
  title: "{{< var PROGRAM_NAME >}} {{< var VERSION >}}"
  subtitle: Programming Manual
  description: '{{< var PROGRAM_DESCRIPTION >}}'
  author: '{{< var PROGRAM_AUTHOR >}}'
  date: today
  date-format: "YYYY"
  output-file: "readability-studio-api"
  language: en
  search: false
  chapters:
    - index.qmd
    - part: "Classes"
      chapters:
      - standard-project.qmd
      - batch-project.qmd
    - part: "Libraries"
      chapters:
      - libapp.qmd
      - libdebug.qmd
    - part: "Support Types"
      chapters:
      - enums.qmd
format:
  pdf:
    documentclass: LegrandOrangeBook
    template: latex/default.tex
    include-in-header: latex/preamble.tex
    latex-engine: xelatex
    keep-tex: true
    citation-package: biblatex
    lot: false
    code-block-bg: false
    CJKmainfont: NotoSerifJP
    CJKoptions:
      - Path=./fonts/NotoSerifJP/
      - Extension=.ttf
      - UprightFont=*-VariableFontwght
    linkcolor: black
    citecolor: black
  html:
    theme: cosmo
    html-math-method: katex
    css: style.css
    smooth-scroll: true
