```{r}
#| include: false
#| eval: true

source('../R/appdown.r')
```

## Open-Source Tools & Content {.unnumbered}

The following open-source software, artwork, and example files were used to create *{{< var PROGRAM_NAME >}}*.

### Documentation Software & Templates {-}
***

#### *Doxygen* {-}

Doxygen is the de facto standard tool for generating documentation from annotated C++ sources,
but it also supports other popular programming languages such as C, Objective-C, C#, PHP, Java, Python,
IDL (Corba, Microsoft, and UNO/OpenOffice flavors), Fortran, VHDL and to some extent D.

[https://doxygen.nl/](https://doxygen.nl/)

### *Legrand Orange Book* {-}

Highly themable {{< latex >}} book template.

[https://www.latextemplates.com/template/the-legrand-orange-book](https://www.latextemplates.com/template/the-legrand-orange-book)

#### *LibreOffice* {-}

LibreOffice is a free and powerful office suite, and a successor to OpenOffice.org (commonly known as OpenOffice).
Its clean interface and feature-rich tools help you unleash your creativity and enhance your productivity.

[https://www.libreoffice.org/](https://www.libreoffice.org/)

#### *Pandoc* {-}

A universal document converter.

If you need to convert files from one markup format into another, pandoc is your swiss-army knife.

[https://pandoc.org/](https://pandoc.org/)

#### *Quarto* {-}

An open-source scientific and technical publishing system.

[https://quarto.org](https://quarto.org)

### Software Development, Quality Assurance & Packaging Software {-}
***

#### *Catch2* {-}

Catch2 is mainly a unit testing framework for C++, but it also provides basic micro-benchmarking features, and simple BDD macros.

[https://github.com/catchorg/Catch2](https://github.com/catchorg/Catch2)

#### *Clang* {-}

A C language family frontend for LLVM.

The Clang project provides a language front-end and tooling infrastructure for languages in the C language family
(C, C++, Objective-C/C++, OpenCL, CUDA, and RenderScript) for the LLVM project.
Both a GCC-compatible compiler driver (clang) and an MSVC-compatible compiler driver (clang-cl.exe) are provided.
You can get and build the source today.

[https://clang.llvm.org/](https://clang.llvm.org/)

#### *CMake* {-}

CMake is an open-source, cross-platform family of tools designed to build, test and package software.

[https://cmake.org/](https://cmake.org/)

#### *GCC*, the GNU Compiler Collection {-}

The GNU Compiler Collection includes front ends for C, C++, Objective-C, Fortran, Ada, Go, and D, as well as libraries for these languages (libstdc++,...).
GCC was originally written as the compiler for the GNU operating system.
The GNU system was developed to be 100% free software, free in the sense that it respects the user's freedom.  

R is a free software environment for statistical computing and graphics.
It compiles and runs on a wide variety of UNIX platforms, Windows and macOS.

[https://www.gnu.org/](https://www.gnu.org/)

#### *git* {-}

Git is a free and open source distributed version control system designed to handle everything from small to very large projects with speed and efficiency.

[https://git-scm.com/](https://git-scm.com/)

#### *Inno Setup* {-}

Inno Setup is a free installer for Windows programs by Jordan Russell and Martijn Laan.
First introduced in 1997, Inno Setup today rivals and even surpasses many commercial installers in feature set and stability.

[https://jrsoftware.org](https://jrsoftware.org)

### Artwork Editing Software {-}
***

#### *GNU Image Manipulation Program* {-}
The Free & Open Source Image Editor.

[https://www.gimp.org/](https://www.gimp.org/)

#### *Inkscape* {-}
Inkscape is a professional vector graphics editor for Linux, Windows and macOS.
It's free and open source.

[https://inkscape.org/](https://inkscape.org/)

### Data Analysis Software {-}
***

#### *R* {-}
R is a free software environment for statistical computing and graphics.
It compiles and runs on a wide variety of UNIX platforms, Windows and MacOS.

[https://www.r-project.org/](https://www.r-project.org/)

#### *RStudio* {-}

Open source and enterprise-ready professional software for data science.

[https://rstudio.com/](https://rstudio.com/)

### Content {-}
***

#### Project Gutenberg {-}

Project Gutenberg is a library of over 60,000 free eBooks.
Choose among free epub and Kindle eBooks, download them or read them online.
You will find the world's great literature here, with focus on older works for which U.S. copyright has expired.
Thousands of volunteers digitized and diligently proofread the eBooks, for enjoyment and education.

[https://www.gutenberg.org/](https://www.gutenberg.org/)

#### Free SVG.org {-}

Free SVG vector files. 

Download and upload SVG images with CC0 public domain license.

[https://freesvg.org/](https://freesvg.org/)

#### Google Fonts {-}

*Playfair Display*, designed by Claus Eggers Sørensen.
*Inter*, designed by Rasmus Andersson.
*Inconsolata*, designed by Raph Levien.
*Playfair Display*, designed by Claus Eggers Sørensen.
*Noto Sans Japanese*, created by Google, inc.

All fonts licensed under the SIL Open Font License Version 1.1.

[https://fonts.google.com](https://fonts.google.com)

#### National Library of Medicine {-}

Images from the History of Medicine (IHM) collection.

Images licensed under the Public Domain Mark 1.0 Universal Deed.

[https://collections.nlm.nih.gov](https://collections.nlm.nih.gov)
