name: macOS Unit Tests

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: unit-tests
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'

      - name: Build & run tests
        run: |
             brew install grep
             cd ..
             git clone https://github.com/catchorg/Catch2.git
             cd ReadabilityStudio/tests
             cmake ./
             make -j4
             cd bin
             ./RSTestRunner > results.txt 2>&1
             cat results.txt
             ./RSTestRunner --reporter JUnit::out=rs-junit.xml
             errors=$(cat rs-junit.xml | ggrep -Po '(errors)="\K[^"]*')
             failures=$(cat rs-junit.xml | ggrep -Po '(failures)="\K[^"]*')
             if [ "$errors" -gt 0 ]; then
               echo "Error count is: ${errors}"
               exit 1
             fi
             if [ "$failures" -gt 0 ]; then
               echo "Failure count is: ${failures}"
               exit 1
             fi
